CREATE TABLE USERS(
	USERID VARCHAR2(200),
	PASSWORD VARCHAR2(200) NOT NULL,
	NAME VARCHAR2(200) NOT NULL,
	PHONE VARCHAR2(200) NOT NULL,
	EMAIL VARCHAR2(200) NOT NULL,
	CONSTRAINT USER_PK PRIMARY KEY (USERID)
)

CREATE TABLE NOTICE(
	BOARDNUM NUMBER,
	USERID VARCHAR2(200),
	BOARDTITLE VARCHAR2(200) NOT NULL,
	BOARDDATE VARCHAR2(200) DEFAULT SYSDATE NOT NULL,
	BOARDCONTENTS CLOB NOT NULL,
	CONSTRAINT NOTICE_PK PRIMARY KEY (BOARDNUM),
	CONSTRAINT N_U_FK FOREIGN KEY (USERID) REFERENCES USERS(USERID) ON DELETE CASCADE
)

CREATE TABLE BOARD(
	BOARDNUM NUMBER,
	USERID VARCHAR2(200),
	BOARDTITLE VARCHAR2(200) NOT NULL,
	BOARDCONTENTS CLOB NOT NULL,
	BOARDDATE DATE DEFAULT SYSDATE NOT NULL,
	CATEGORY NUMBER NOT NULL,
	RATING NUMBER NOT NULL,
	FAVORITE NUMBER NOT NULL,
	BOARDHITS NUMBER DEFAULT 0 NOT NULL,
	LOCATION VARCHAR2(200) NOT NULL,
	CONSTRAINT BOARD_PK PRIMARY KEY (BOARDNUM),
	CONSTRAINT B_U_FK FOREIGN KEY (USERID) REFERENCES USERS(USERID) ON DELETE CASCADE
)

CREATE TABLE QNA(
	BOARDNUM NUMBER,
	USERID VARCHAR2(200),
	BOARDTITLE VARCHAR2(200) NOT NULL,
	BOARDCONTENTS CLOB NOT NULL,
	BOARDDATE DATE DEFAULT SYSDATE NOT NULL,
	BOARDDEPTH NUMBER NOT NULL,
	BOARDREF NUMBER NOT NULL,
	BOARDSTEP NUMBER NOT NULL,
	CONSTRAINT QNA_PK PRIMARY KEY (BOARDNUM),
	CONSTRAINT Q_U_FK FOREIGN KEY (USERID) REFERENCES USERS(USERID) ON DELETE CASCADE
)

CREATE TABLE COMMENTS(
	BOARDNUM NUMBER,
	USERID VARCHAR2(200),
	BOARDDATE DATE DEFAULT SYSDATE NOT NULL,
	BOARDCONTENTS CLOB NOT NULL,
	CONSTRAINT C_B_FK FOREIGN KEY (BOARDNUM) REFERENCES BOARD(BOARDNUM) ON DELETE CASCADE,
	CONSTRAINT C_U_FK FOREIGN KEY (USERID) REFERENCES USERS(USERID)
);

ALTER TABLE "COMMENTS" ADD CONSTRAINT "COMMENT_PK" PRIMARY KEY (
	"USERID", "BOARDNUM"
);


CREATE TABLE FAVORITE(
	BOARDNUM NUMBER,
	USERID VARCHAR2(200),
	CONSTRAINT F_B_FK FOREIGN KEY (BOARDNUM) REFERENCES BOARD(BOARDNUM) ON DELETE CASCADE,
	CONSTRAINT F_U_FK FOREIGN KEY (USERID) REFERENCES USERS(USERID)
)

ALTER TABLE "FAVORITE" ADD CONSTRAINT "FAVORITE_PK" PRIMARY KEY (
	"USERID", "BOARDNUM"
);



CREATE TABLE IMAGES(
	FILENUM NUMBER,
	FILENAME VARCHAR2(200) NOT NULL,
	BOARDNUM NUMBER,
	OLDNAME VARCHAR2(200) NOT NULL,
	CONSTRAINT IMAGES_PK PRIMARY KEY (FILENUM),
	CONSTRAINT I_B_FK FOREIGN KEY (BOARDNUM) REFERENCES BOARD(BOARDNUM)
)


CREATE SEQUENCE PDT_SEQ
CREATE SEQUENCE FILE_SEQ
CREATE SEQUENCE BOARD_SEQ

SELECT * FROM TABS
SELECT * FROM USER_CONSTRAINTS
SELECT * FROM USER_SEQUENCES

------------------------------------------------
-------------------FLIGHTS----------------------

CREATE TABLE FLIGHTSUPDATE(
	FLIGHTNUM VARCHAR2(200),
	VIHICLEID VARCHAR2(200) NOT NULL,
	AIRLINENM VARCHAR2(200) NOT NULL,
	DEPPLANDTIME DATE NOT NULL,
	ARRPLANDTIME DATE NOT NULL,
	DEPAIRPORTNM VARCHAR2(200) NOT NULL,
	ARRAIRPORTNM VARCHAR2(200) NOT NULL,
	ECONOMYCHARGE NUMBER NOT NULL,
	PRESTIGECHARGE NUMBER NOT NULL,
	CONSTRAINT FLIGHTSUPDATE_PK PRIMARY KEY (FLIGHTNUM)
)

CREATE TABLE FLIGHT(
	FLIGHTNUM VARCHAR2(200),
	VIHICLEID VARCHAR2(200) NOT NULL,
	AIRLINENM VARCHAR2(200) NOT NULL,
	DEPPLANDTIME DATE NOT NULL,
	ARRPLANDTIME DATE NOT NULL,
	DEPAIRPORTNM VARCHAR2(200) NOT NULL,
	ARRAIRPORTNM VARCHAR2(200) NOT NULL,
	ECONOMYCHARGE NUMBER NOT NULL,
	PRESTIGECHARGE NUMBER NOT NULL,
	CONSTRAINT FLIGHTS_PK PRIMARY KEY (FLIGHTNUM),
	CONSTRAINT F_A_FK FOREIGN KEY (AIRLINENM) REFERENCES AIRLINE(AIRLINENM)
)


CREATE TABLE AIRPORT(
	AIRPORTID VARCHAR2(200) PRIMARY KEY,
	AIRPORTNM VARCHAR2(200) NOT NULL
)

CREATE TABLE AIRLINE(
	AIRLINENM VARCHAR2(200) PRIMARY KEY,
	AIRLINEID VARCHAR2(200) NOT NULL
)

CREATE TABLE RESERVATIONS(
	RESERVNUM VARCHAR2(200),
	USERID VARCHAR2(200),
	CONSTRAINT RESERV_PK PRIMARY KEY (RESERVNUM),
	CONSTRAINT R_U_FK FOREIGN KEY(USERID) REFERENCES USERS(USERID)
)

ALTER TABLE RESERVATIONS ADD (PAYMENT VARCHAR2(200) NOT NULL)
ALTER TABLE RESERVATIONS ADD (AMOUNT NUMBER NOT NULL)

CREATE TABLE BOARDINGINFO(
	NAME VARCHAR2(200) NOT NULL,
	BIRTH VARCHAR2(200) NOT NULL,
	RESERVNUM VARCHAR2(200),
	DIV VARCHAR2(200) NOT NULL,
	FNUMGO VARCHAR2(200) NOT NULL,
	FNUMCOME VARCHAR2(200) NOT NULL,
	CONSTRAINT B_R_FK FOREIGN KEY(RESERVNUM) REFERENCES RESERVATIONS(RESERVNUM)
)

ALTER TABLE "BOARDINGINFO" ADD CONSTRAINT "BOARDINGINFO_PK" PRIMARY KEY (
	"NAME", "BIRTH", "RESERVNUM"
);

ALTER TABLE BOARDINGINFO ADD (CHARGEDIV VARCHAR2(200) NOT NULL)